"""new-user-table

Revision ID: 319e68e922d9
Revises: ea0afae5ce68
Create Date: 2023-11-28 18:26:21.210947

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '319e68e922d9'
down_revision = 'ea0afae5ce68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['users_id'], ['id'])

    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_index('TT_price')
        batch_op.drop_index('coupon_code')
        batch_op.drop_index('price')
        batch_op.drop_index('promotion')
        batch_op.drop_index('status')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint('notification_ibfk_1', type_='foreignkey')
        batch_op.drop_column('orders_id')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('order_date',
               existing_type=mysql.VARCHAR(length=35),
               nullable=True)
        batch_op.drop_constraint('orders_ibfk_2', type_='foreignkey')
        batch_op.drop_column('products_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_ibfk_1', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key('users_ibfk_1', 'locations', ['locations_id'], ['id'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('products_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('orders_ibfk_2', 'products', ['products_id'], ['id'])
        batch_op.alter_column('order_date',
               existing_type=mysql.VARCHAR(length=35),
               nullable=False)

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orders_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('notification_ibfk_1', 'orders', ['orders_id'], ['id'])

    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.create_index('status', ['status'], unique=False)
        batch_op.create_index('promotion', ['promotion'], unique=False)
        batch_op.create_index('price', ['price'], unique=False)
        batch_op.create_index('coupon_code', ['coupon_code'], unique=False)
        batch_op.create_index('TT_price', ['TT_price'], unique=False)

    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
